version: 0.2
phases:
  preBuild:
    commands:
      - cd springboot_backend
  build:
    commands:
      - echo Entered the build phase....
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - springboot_backend/target/springboot_backend-0.0.1-SNAPSHOT.jar
  discard-paths: yes
