version: 0.2
phases:
  pre_build:
    commands:
      - cd springboot_backend
  build:
    commands:
      - echo Entered the build phase....
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/springboot_backend-0.0.1-SNAPSHOT.jar
  discard-paths: yes
