version: 0.2
phases:
  build:
    commands:
      - cd springboot_backend
      - echo Entered the build phase............
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/springboot_backend.jar
  discard-paths: yes
