version: 0.2
phases:
  build:
    commands:
      - cd springboot_backend
      - echo Entered the build phase....
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/srpingboot_backend.jar
  discard-paths: yes
